[default.extend-words]
# random strings
yello = "yello"
datas = "datas"

# tech abbreviations
ND = "ND"
RTO = "RTO"
AKS = "AKS"

# tech terms
excluder = "excluder"
flate = "flate"
consts = "consts"

[files]
extend-exclude = [
  "pnpm-lock.yaml",
  "*/**/df-functions.md",
  "**/*.svg"
]
